# Generated by Django 3.2.6 on 2022-02-01 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220201_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='correct_choice',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='first_question',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='fourth_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='second_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='third_question',
        ),
        migrations.AddField(
            model_name='question',
            name='first_choice',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='fourth_choice',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='second_choice',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='third_choice',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
