# Generated by Django 3.2.6 on 2022-02-02 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220202_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='app.classroom'),
        ),
    ]
