# Generated by Django 3.2.6 on 2022-02-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlesson',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
