# Generated by Django 3.2.6 on 2022-02-04 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_userlesson_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_lesson', to='app.lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_lesson', to='app.lesson'),
        ),
    ]
