# Generated by Django 3.2.6 on 2022-02-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20220204_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
