# Generated by Django 3.2.6 on 2022-02-04 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_classroom_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlesson',
            name='completed_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
