# Generated by Django 3.2.6 on 2022-03-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20220306_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
