# Generated by Django 3.2.6 on 2022-03-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_quiz_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
