# Generated by Django 3.2.6 on 2022-03-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_question', to='app.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_question', to='app.question'),
        ),
    ]
