# Generated by Django 3.2.6 on 2022-03-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_userquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquiz',
            name='completed',
        ),
    ]
