# Generated by Django 3.2.6 on 2022-03-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_userquiz_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='result',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userquiz',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
