# Generated by Django 3.2.6 on 2022-03-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20220307_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='result',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
